### ISSUE TITLE
device.type on iPhone XS, iOS 13.5 on Safari + Chrome returns null.

### ISSUE THREAD

**Issue by darkmeton** [etienne-martin/device-detector-js#89]
this is the device info 
`{
client :{ type: 'browser', name:'Mobile Safari', version:'13.1', engine: 'WebKit', engineVersion:'605.1'},
os:{name:'iOS', 'version:'13.5', platform:''},
device: {type:'', brand:'apple', model:''},
bot: null
}`

**Comment by Findus23** [comment]
Hi,

Can you please share the full user agent of the device?

**Comment by etienne-martin** [comment]
Hi @darkmeton do you know if this is also an issue with the [php version](https://github.com/matomo-org/device-detector)?

**Comment by AndyWorral** [comment]
I found the following User Agent executes differently when ran on iPad (os 12) vs desktop (chrome)

"Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"

You get the following on Desktop

```{
"client":{
"type":"browser"
"name":"Mobile Safari"
"version":"12.0"
"engine":"WebKit"
"engineVersion":"605.1"
}
"os":{
"name":"iOS"
"version":"12.1"
"platform":""
}
"device":{
"type":"tablet"
"brand":"Apple"
"model":"iPad"
}
"bot":NULL
}
```

But in Safari on iPad w/ os 12 you do not get the device type and model
```
{
"client":{
"type":"browser"
"name":"Mobile Safari"
"version":"12.0"
"engine":"WebKit"
"engineVersion":"605.1"
}
"os":{
"name":"iOS"
"version":"12.1"
"platform":""
}
"device":{
"type":""
"brand":"Apple"
"model":""
}
"bot":NULL
}
```

I get the same results in my code and on the test page.

**Comment by Findus23** [comment]
> But in Safari on iPad w/ os 12 you do not get the device type and model

This is completly working as expected.

Since some time, Apple has stopped sending an iPad user agent on iOS.

The current user agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15` does not contain any information about the fact that this is a tablet and therefore DeviceDetector correctly detects it as a MacOS device:

https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_4)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F13.1.1%20Safari%2F605.1.15

(I am talking about the PHP devicedetector, but the same is probably also true for the JS port)

**Comment by etienne-martin** [comment]
Same behavior for the javascript version. This is expected because Safari on iOS no longer sends the device fragment.  

https://lx3rzx16x9.csb.app/#Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_4)%20AppleWebKit/605.1.15%20(KHTML,%20like%20Gecko)%20Version/13.1.1%20Safari/605.1.15

**Comment by etienne-martin** [comment]
Oh sorry I get it now! Yes this is because Safari doesn't support lookbehind yet (See related issue: https://github.com/etienne-martin/device-detector-js/issues/31).

Also please note that running device-detector in a browser environment is not recommended: https://github.com/etienne-martin/device-detector-js#browser

I will update the disclaimer to mention the inconsistencies between browsers.
