### ISSUE TITLE
Whats App not detected

### ISSUE THREAD

**Issue by tsavecodes** [etienne-martin/device-detector-js#90]
The bots.json files require an entry for What's App.

Here is an example of a user agent. I was able to work around this (without forking) just by testing the string for "WhatsApp" but it might be nice to get into this package.

WhatsApp/2.16.259 Mozilla/5.0(Android/4.3 Device/GalaxyS3) AppleWebKit/537.36 (KHTML, like Gecko)

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/device-detector/issues/5463

**Comment by etienne-martin** [comment]
Hi @tsavecodes, I'm going to close the issue since it is about missing/incorrect detection and is not related to a problem with the javascript library itself.

Missing/incorrect detections should be reported at https://github.com/matomo-org/device-detector/issues instead of this repo.

Once a fix land in the [php version](https://github.com/matomo-org/device-detector/issues), it will trickle down to this library.
